name: Validate Data Integrity

on:
  push:
    paths:
      - 'data/**'
  pull_request:
    paths:
      - 'data/**'

jobs:
  validate:
    name: ðŸ” Validate GIS Data Integrity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install minimal validation deps
        run: pip install geopandas rasterio pyproj fiona

      - name: Run data validation checks
        run: python scripts/validate_data.py

      - name: Write validation summary
        if: always()
        run: |
          echo "## ðŸ” Data Validation Results" >> $GITHUB_STEP_SUMMARY
          cat outputs/validation_report.txt >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No validation report generated" >> $GITHUB_STEP_SUMMARY
